export const BIST_STOCKS = [
  { symbol: 'THYAO', name: 'Türk Hava Yolları' },
  { symbol: 'EREGL', name: 'Ereğli Demir Çelik' },
  { symbol: 'TUPRS', name: 'Tüpraş' },
  { symbol: 'SISE', name: 'Şişecam' },
  { symbol: 'KCHOL', name: 'Koç Holding' },
  { symbol: 'SAHOL', name: 'Sabancı Holding' },
  { symbol: 'AKBNK', name: 'Akbank' },
  { symbol: 'ISCTR', name: 'İş Bankası (C)' },
  { symbol: 'YKBNK', name: 'Yapı Kredi' },
  { symbol: 'GARAN', name: 'Garanti BBVA' },
  { symbol: 'BIMAS', name: 'BİM Mağazalar' },
  { symbol: 'FROTO', name: 'Ford Otosan' },
  { symbol: 'ASELS', name: 'Aselsan' },
  { symbol: 'SASA', name: 'Sasa Polyester' },
  { symbol: 'HEKTS', name: 'Hektaş' },
  { symbol: 'ENKAI', name: 'Enka İnşaat' },
  { symbol: 'TCELL', name: 'Turkcell' },
  { symbol: 'PGSUS', name: 'Pegasus' },
  { symbol: 'TTKOM', name: 'Türk Telekom' },
  { symbol: 'TOASO', name: 'Tofaş' },
  { symbol: 'ARCLK', name: 'Arçelik' },
  { symbol: 'KRDMD', name: 'Kardemir (D)' },
  { symbol: 'PETKM', name: 'Petkim' },
  { symbol: 'KOZAL', name: 'Koza Altın' },
  { symbol: 'ODAS', name: 'Odaş Elektrik' },
  { symbol: 'ASTOR', name: 'Astor Enerji' },
  { symbol: 'ALFAS', name: 'Alfa Solar Enerji' },
  { symbol: 'GESAN', name: 'Girişim Elektrik' },
  { symbol: 'SMRTG', name: 'Smart Güneş Tekno' },
  { symbol: 'EUPWR', name: 'Europower Enerji' },
  { symbol: 'MGROS', name: 'Migros' },
  { symbol: 'DOAS', name: 'Doğuş Otomotiv' },
  { symbol: 'TAVHL', name: 'TAV Havalimanları' },
  { symbol: 'OTKAR', name: 'Otokar' },
  { symbol: 'VESBE', name: 'Vestel Beyaz Eşya' },
  { symbol: 'VESTL', name: 'Vestel' },
  { symbol: 'CIMSA', name: 'Çimsa' },
  { symbol: 'AKSA', name: 'Aksa Akrilik' },
  { symbol: 'TKFEN', name: 'Tekfen Holding' },
  { symbol: 'GUBRF', name: 'Gübre Fabrikaları' },
  { symbol: 'HALKB', name: 'Halkbank' },
  { symbol: 'VAKBN', name: 'Vakıfbank' },
  { symbol: 'TSKB', name: 'TSKB' },
  { symbol: 'SKBNK', name: 'Şekerbank' },
  { symbol: 'ALBRK', name: 'Albaraka Türk' },
  { symbol: 'EKGYO', name: 'Emlak Konut GYO' },
  { symbol: 'ISGYO', name: 'İş GYO' },
  { symbol: 'ZRGYO', name: 'Ziraat GYO' },
  { symbol: 'TRGYO', name: 'Torunlar GYO' },
  { symbol: 'ENJSA', name: 'Enerjisa' },
  { symbol: 'AKSEN', name: 'Aksa Enerji' },
  { symbol: 'GWIND', name: 'Galata Wind Enerji' },
  { symbol: 'AYDEM', name: 'Aydem Yenilenebilir' },
  { symbol: 'ZOREN', name: 'Zorlu Enerji' },
  { symbol: 'CANTE', name: 'Çan2 Termik' },
  { symbol: 'QUAGR', name: 'Qua Granite' },
  { symbol: 'KCAER', name: 'Kocaer Çelik' },
  { symbol: 'BRSAN', name: 'Borusan Boru' },
  { symbol: 'EGEEN', name: 'Ege Endüstri' },
  { symbol: 'KORDS', name: 'Kordsa' },
  { symbol: 'LOGO', name: 'Logo Yazılım' },
  { symbol: 'MIATK', name: 'Mia Teknoloji' },
  { symbol: 'KMPUR', name: 'Kimteks Poliüretan' },
  { symbol: 'SUWEN', name: 'Suwen' },
  { symbol: 'KZBGY', name: 'Kızılbük GYO' },
  { symbol: 'KLSER', name: 'Kaleseramik' },
  { symbol: 'CWENE', name: 'CW Enerji' },
  { symbol: 'CVKMD', name: 'CVK Maden' },
  { symbol: 'BIENY', name: 'Bien Yapı' },
  { symbol: 'EUREN', name: 'Europen Endüstri' },
  { symbol: 'PNLSN', name: 'Panelsan' },
  { symbol: 'SDTTR', name: 'SDT Uzay ve Savunma' },
  { symbol: 'ONCSM', name: 'Oncosem Onkolojik' },
  { symbol: 'SOKE', name: 'Söke Değirmencilik' },
  { symbol: 'MACKO', name: 'Maçkolik' },
  { symbol: 'BVSAN', name: 'Bülbüloğlu Vinç' },
  { symbol: 'KTLEV', name: 'Katılımevim' },
  { symbol: 'FZLGY', name: 'Fuzul GYO' },
  { symbol: 'ASGYO', name: 'Asce GYO' },
  { symbol: 'OFSYM', name: 'Ofis Yem' },
  { symbol: 'TATEN', name: 'Tatlıpınar Enerji' },
  { symbol: 'IZENR', name: 'İzdemir Enerji' },
  { symbol: 'ENERY', name: 'Enerya Enerji' },
  { symbol: 'BYDNR', name: 'Baydöner' },
  { symbol: 'KUZGO', name: 'Kuzey Boru' },
  { symbol: 'TABGD', name: 'TAB Gıda' },
  { symbol: 'LILAK', name: 'Lila Kağıt' },
  { symbol: 'KOCMT', name: 'Koç Metalurji' },
  { symbol: 'OBAMS', name: 'Oba Makarnacılık' },
  { symbol: 'EBEBK', name: 'Ebebek' },
  { symbol: 'MHRGY', name: 'MHR GYO' },
  { symbol: 'MEKAG', name: 'Meka Beton' },
  { symbol: 'MARBL', name: 'Tureks Turunç Madencilik' },
  { symbol: 'DOFER', name: 'Dofer Yapı' },
  { symbol: 'BORLS', name: 'Borlease Otomotiv' },
  { symbol: 'REEDR', name: 'Reeder Teknoloji' },
  { symbol: 'SURGY', name: 'Sur Tatil Evleri GYO' },
  { symbol: 'KBORU', name: 'Kuzey Boru' },
  { symbol: 'MEGMT', name: 'Mega Metal' },
  { symbol: 'SKYMD', name: 'Şeker Yatırım' }
];

// Fallback pricing logic for newly added unknown stocks to ensure the UI works
export const getLivePriceForStock = (ticker: string, fallbackBasePrice: number = 100): number => {
  // If it's a known stock from demoData, we can use it.
  // Otherwise, we generate a stable but slightly fluctuating price based on the string hash so it's consistent.
  let hash = 0;
  for (let i = 0; i < ticker.length; i++) {
    hash = ticker.charCodeAt(i) + ((hash << 5) - hash);
  }
  const randomFactor = (Math.abs(hash) % 100) / 100; // 0 to 1
  
  // Create a price that is somewhat near the fallback (buy) price but varies slightly
  // In a real app, this would be an async API call to Yahoo Finance or similar
  const variation = (randomFactor * 0.1) - 0.05; // -5% to +5%
  
  if (fallbackBasePrice <= 0) fallbackBasePrice = 100;
  
  return Number((fallbackBasePrice * (1 + variation)).toFixed(2));
};
